#!/usr/bin/env bash

######################################################################
## Iniitalize the environment
##
this="${BASH_SOURCE-$0}"
bin=$( cd -P -- "$( dirname -- "${this}" )" && pwd -P )
script="$( basename -- "${this}" )"
this="${bin}/${script}"
timestamp="$( date +%Y%m%d_%H%M%S )"
fqdn="$( hostname -f )"
debug_level=1

set -e
set -u
set -o pipefail

scratch=$( mktemp -d -t scratch.tmp.XXXXXXXXXX )
function finish {
    rm -Rf "${scratch}"
}
trap finish EXIT

IFS=$'\n\t'

echo "[minikube][install-addon][ingress]"
minikube addons enable ingress


echo "[minikube][version]"
minikube addons list

echo "

    Minikube addons install finished.


    Helpful commands:

        minikube addons list
"


