{{- range $ingressKey, $ingressValue := .Values.ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressKey }}
  labels:
    {{- include "spot-generic.labels" . | nindent 4 }}
  {{- with $ingressValue.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $ingressValue.tls }}
  tls:
    {{- range $ingressValue.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $hostKey, $hostValue := $ingressValue.hosts }}
    - host: {{ $hostKey | quote }}
      http:
        {{- with $hostValue.paths }}
        paths:
          {{- toYaml . nindent 10 }}
        {{- end }}
    {{- end }}
{{- end }}
