{{- range $pvcKey, $pvcValue := .Values.persistentVolumeClaims }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvcKey }}
  labels:
    {{- include "spot-generic.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $pvcValue.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.globals.storageClass }}
  storageClassName: {{ .Values.globals.storageClass }}
  {{- else }}
  storageClassName: {{ $pvcValue.storageClass | default "gp2" }}
  {{- end }}
{{- end }}
