services:
  geoserver:
    container_name: geoserver
    image: ${GEOSERVER_IMAGE}:${GEOSERVER_TAG}
    restart: always
    environment:
      - "extraJavaOpts=\"${GEOSERVER_OPTS}\""
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,HEAD,OPTIONS
      - CORS_ALLOWED_HEADERS=*
      - CORS_ALLOW_CREDENTIALS=false
    ports:
      - ${GEOSERVER_PORT}:8080
    volumes:
      - ${PWD}/data/geoserver:/opt/geoserver_data
    networks:
      - postgis_spot_network

networks:
  postgis_spot_network:
    external: true

