services:
  postgis:
    container_name: postgis
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=${PGSQL_DB}
      - POSTGRES_USER=${PGSQL_DB_USERNAME}
      - POSTGRES_PASSWORD=${PGSQL_DB_PASSWORD}
    ports:
      - ${PGSQL_DB_PORT}:5432
    volumes:
      - ${PWD}/data/pgsql:/var/lib/postgresql/data
    networks:
      - spot_network

networks:
  spot_network:
    driver: bridge