apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: spot-services-pgsql-tgb
  namespace: spot
spec:
  serviceRef:
    name: spot-postgresql
    port: 5432
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:058227136789:targetgroup/spot-services-pgsql/a40c36ca01b57dc2
