apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spot-tileserver-gl.fullname" . }}
  labels:
    {{- include "spot-tileserver-gl.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "spot-tileserver-gl.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spot-tileserver-gl.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "spot-tileserver-gl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.podCommand }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ range $envKey, $envValue := .Values.envs }}
            - name: {{ $envKey }}
              value: {{ $envValue | quote }}
            {{ end }}
          ports:
            - name: private-http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: {{ include "spot-tileserver-gl.fullname" . }}
              mountPath: {{ .Values.persistence.mountPath | default "/data" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "spot-tileserver-gl.fullname" . }}
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "spot-tileserver-gl.fullname" . }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
